targets:
  $default:
    builders:
      json_serializable:
        options:
          # json のデシリアライズ時に発生する Exception を CheckedFromJsonException にまとめる
          checked: true
      # https://github.com/dart-lang/source_gen#ignore_for_file
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
